language: cpp
sudo: required
dist: trusty
matrix:
  include:
    - os: osx
      compiler: clang
    - os: linux
      compiler: gcc
script:
- mkdir release
- cd release
- cmake -DCMAKE_BUILD_TYPE=Release DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCMAKE_C_COMPILER=$C_COMPILER .. && make
- cd ..
- mkdir debug
- cd debug
- cmake -DCMAKE_BUILD_TYPE=Debug DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCMAKE_C_COMPILER=$C_COMPILER .. && make
