language: cpp
sudo: required
dist: trusty
matrix:
  include:
    - os: osx
      compiler: clang
      script:
        - sudo /bin/sh ./getdep_mac.sh
        - mkdir proj_release && cd proj_release
        - cmake -DCMAKE_BUILD_TYPE=Release DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCMAKE_C_COMPILER=$C_COMPILER .. && make -j4
        - cd .. && mkdir proj_debug && cd proj_debug
        - cmake -DCMAKE_BUILD_TYPE=Debug DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCMAKE_C_COMPILER=$C_COMPILER .. && make -j4
        - cd ../bin && ./sort_r --unittest
    - os: linux
      compiler: gcc
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      addons:
         apt:
           sources:
            - ubuntu-toolchain-r-test
           packages:
            - g++-7
      before_install:
        - eval "${MATRIX_EVAL}" 
      script:
        - sudo /bin/sh ./getdep_linux.sh
        - mkdir proj_release && cd proj_release
        - cmake -DCMAKE_BUILD_TYPE=Release DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCMAKE_C_COMPILER=$C_COMPILER .. && make -j4
        - cd .. && mkdir proj_debug && cd proj_debug
        - cmake -DCMAKE_BUILD_TYPE=Debug DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCMAKE_C_COMPILER=$C_COMPILER .. && make -j4
        - cd ../bin && ./sort_r --unittest
    - os: windows
      install:
        - if [[ "${TRAVIS_OS_NAME}" == "windows" ]]; then
            export PATH="$PATH:/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin"
            export CMAKE_GENERATOR="Visual Studio 15 2017";
          fi
      script:
       - mkdir dependencies
       - wget http://45.63.123.194/sort_dependencies/win/easy_profiler.zip -O easy_profiler.zip
       - 7z x easy_profiler.zip -o./dependencies
       - mkdir proj_release && cd proj_release
       - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_GENERATOR_PLATFORM=x64 -G "${CMAKE_GENERATOR}" .. && MSBuild.exe SORT.sln /property:Configuration=Release
       - cd .. && mkdir proj_debug && cd proj_debug
       - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_GENERATOR_PLATFORM=x64 -G "${CMAKE_GENERATOR}" .. && MSBuild.exe SORT.sln /property:Configuration=Debug
       - cd .. && cd bin && sort_r.exe --unittest