language: cpp
sudo: required
dist: trusty
matrix:
  include:
    - os: osx
      compiler: clang
    - os: linux
      compiler: gcc
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      addons:
         apt:
           sources:
            - ubuntu-toolchain-r-test
           packages:
            - g++-7

before_install:
    - eval "${MATRIX_EVAL}"
    
script:
- sudo /bin/sh ./getdep_linux.sh
- mkdir proj_release
- cd proj_release
- cmake -DCMAKE_BUILD_TYPE=Release DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCMAKE_C_COMPILER=$C_COMPILER .. && make -j4
- cd ..
- mkdir proj_debug
- cd proj_debug
- cmake -DCMAKE_BUILD_TYPE=Debug DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCMAKE_C_COMPILER=$C_COMPILER .. && make -j4
