name: Build SORT

on:
  push:
    paths-ignore: 
      - 'blender-plugin/**'
      - 'README.md'
      - '.gitignore'
    branches:
      - master
  pull_request:
    paths-ignore: 
      - 'blender-plugin/**'
      - 'README.md'
      - '.gitignore'
    branches: 
      - master

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Install Dependencies
      run: make update_dep
      shell: cmd
    - name: Build Release Version
      run: make release
      shell: cmd
    - name: Build Debug Version
      run: make debug
      shell: cmd
    - name: Unit Test
      run: |
           cd bin
           sort_r.exe --unittest
      shell: cmd
  macos:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: make update_dep
    - name: Build Release Version
      run: make release
    - name: Build Debug Version
      run: make debug
    - name: Unit Test
      run: cd bin;./sort_r --unittest
  ubuntu_18_04:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Configure Environment
      run: |
           sudo apt-get install libopenexr-dev
           sudo apt-get install libboost-all-dev
           wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
           sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-6.0 main"
           sudo apt-get update
           sudo apt-get install -y clang-6.0
           make update_dep
    - name: Build Release Version
      run: make release
    - name: Build Debug Version
      run: make debug
    - name: Unit Test
      run: cd bin;./sort_r --unittest
