name: MacOS

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: make update_dep
    - name: Build Release Version
      run: make release
    - name: Build Debug Version
      run: make debug
    - name: Unit Test
      run: cd bin;./sort_r --unittest
