name: Ubuntu

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: Configure Environment
      run: |
           sudo apt-get install libopenexr-dev
           sudo apt-get install libboost-all-dev
           wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
           sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-6.0 main"
           sudo apt-get update
           sudo apt-get install -y clang-6.0
           make update_dep
    - name: Build Release
      run: make release
    - name: Build Debug
      run: make debug
    - name: Unittest
      run: |
           cd bin
           ./sort_r --unittest
